# Generated by Django 4.2.14 on 2024-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepagecontent", old_name="image", new_name="image1",
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
