# Generated by Django 4.2.14 on 2024-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0002_rename_image_homepagecontent_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the activity title", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter the details of the activity"),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
