# Generated by Django 4.2.14 on 2024-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0003_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the project title", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter the project description"),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
